[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/packerlschupfer/ESP32-Logger.git
    https://github.com/packerlschupfer/ESP32-Syslog.git
