[env:esp32dev]
build_flags = -Werror=unused-result
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    symlink://../..
